<!doctype html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Головна сторінка | Магазин "Весна"</title>
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body class="flex flex-col w-full h-dvh mt-auto">
  <?php include './templates/navbar.phtml'; ?>

  <main class="flex flex-1 items-center justify-center bg-slate-50">
    <h1 class="text-2xl font-semibold tracking-tight">Ласкаво просимо до магазину "Весна"</h1>
  </main>

  <?php include './templates/footer.phtml'; ?>
</body>
</html>
